name: Android 12 5.10.236
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      # kernelsu_branch_other:
      #   required: false
      #   type: string
      #   default: ""
      version:
        required: false
        type: string
        default: ""
      use_zram:
        description: 'Enable adding more ZRAM algorithms?'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: 'Enable the BBG anti-format patch?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Enable the KPM feature?'
        required: true
        type: boolean
        default: true
      cancel_susfs:
        description: 'Cancel susfs'
        required: false
        type: boolean
        default: false
      onlyAk3:
        description: 'Upload only AK3 compressed file? (No boot.img, faster)'
        required: false
        type: boolean
        default: false
      build_time:
        description: 'Set the kernel build time (see repository instructions for format).'
        required: false
        type: string
      
  
jobs:
  build-kernel-a12-5-10-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
        #- sub_level: "226"
        #  os_patch_level: "2024-11"
        #  revision: "r8"
        - sub_level: "236"
          os_patch_level: "2025-05"
          revision: "r7"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      # kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      version: ${{ inputs.version || '' }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_kpm: ${{ inputs.use_kpm }}
      supp_op: ${{ inputs.supp_op || false }}
      onlyAk3: ${{ inputs.onlyAk3 || false }}
      build_time: ${{ inputs.build_time || '' }}
      cancel_susfs: ${{ inputs.cancel_susfs || false }}
